[package]
name = "cc-urls"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-compression = { version = "0.4.48", features = ["futures-io", "gzip"] }
futures = "0.3.34"
polars = { version = "0.55.2", features = ["lazy", "parquet", "regex", "strings"] }
rand = "0.10.3"
ratelimit = "2.0.0"
reqwest = { version = "0.13.5", features = ["stream"] }
reqwest-middleware = "0.5.2"
reqwest-retry = "0.9.1"
tikv-jemallocator = "0.7.0"
tokio = { version = "1.53.1", features = ["macros"] }
url = "2.5.8"
